// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_proj1)
QT_DECLARE_EXTERN_RESOURCE(qmake_proj1)
QT_DECLARE_EXTERN_RESOURCE(proj1_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_proj1)

class proj1Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    proj1Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_proj1)
QT_KEEP_RESOURCE(qmlcache_proj1)
QT_KEEP_RESOURCE(qmake_proj1)
QT_KEEP_RESOURCE(proj1_raw_qml_0)
    }
};



#include "proj1plugin_proj1Plugin.moc"
