set(_CATKIN_CURRENT_PACKAGE "proj1_node")
set(proj1_node_VERSION "0.0.0")
set(proj1_node_MAINTAINER "Your Name <your_email@example.com>")
set(proj1_node_PACKAGE_FORMAT "2")
set(proj1_node_BUILD_DEPENDS "roscpp" "qt5-webkit" "qt5-declarative" "std_msgs" "std_stamped_msgs")
set(proj1_node_BUILD_EXPORT_DEPENDS "roscpp" "qt5-webkit" "qt5-declarative" "std_msgs" "std_stamped_msgs")
set(proj1_node_BUILDTOOL_DEPENDS "catkin")
set(proj1_node_BUILDTOOL_EXPORT_DEPENDS )
set(proj1_node_EXEC_DEPENDS "roscpp" "qt5-webkit" "qt5-declarative" "std_msgs" "std_stamped_msgs")
set(proj1_node_RUN_DEPENDS "roscpp" "qt5-webkit" "qt5-declarative" "std_msgs" "std_stamped_msgs")
set(proj1_node_TEST_DEPENDS )
set(proj1_node_DOC_DEPENDS )
set(proj1_node_URL_WEBSITE "")
set(proj1_node_URL_BUGTRACKER "")
set(proj1_node_URL_REPOSITORY "")
set(proj1_node_DEPRECATED "")